<?php

namespace Game;

use App\Actions\Game\CreateGame;
use App\Actions\Game\CreateGamesForExternalApi;
use App\Actions\Game\PostponeGame;
use App\Actions\Game\UpdateGameResult;
use App\Actions\Game\UpdateResultGamesForExternalApi;
use App\Actions\Team\FindOrCreateTeam;
use App\Http\Clients\Common\ApiClient;
use App\InfrastructureServices\GetterGamesExternalEspn;
use App\Models\Competition;
use App\Models\CompetitionPhase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithoutEvents;
use Tests\TestCase;

class UpdateGameForExternalApiTest extends TestCase
{
    use RefreshDatabase;
    use WithoutEvents;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->createGamesToUpdate();
    }

    public function testHappyPath()
    {
        $ApiClient = $this->createMock(ApiClient::class);

        $json = json_decode(file_get_contents(__DIR__ . '/json/espnResponseTestForUpdateResults.json', true), true);

        $ApiClient
            ->method('get')
            ->willReturn($json);

        $GetterGamesExternalApi = new GetterGamesExternalEspn($ApiClient);

        $this->UpdateResultGamesForExternalApi = new UpdateResultGamesForExternalApi(
            $GetterGamesExternalApi,
            app(FindOrCreateTeam::class),
            app(UpdateGameResult::class),
            app(PostponeGame::class)
        );

        $Games = $this
            ->UpdateResultGamesForExternalApi
            ->__invoke($this->Competition, (new \DateTime())->format('Y-m-d H:i:s'));

        $this->assertNotEmpty($Games);
    }

    protected function createGamesToUpdate()
    {
        $ApiClient = $this->createMock(ApiClient::class);

        $json = json_decode(file_get_contents(__DIR__ . '/json/espnResponseTest.json', true), true);

        $ApiClient
            ->method('get')
            ->willReturn($json);

        $GetterGamesExternalApi = new GetterGamesExternalEspn($ApiClient);

        $this->CreateGameForExternalApi = new CreateGamesForExternalApi(
            $GetterGamesExternalApi,
            app(FindOrCreateTeam::class),
            app(CreateGame::class),
        );

        $this->Competition = Competition::factory([
            'name'             => 'English premier league',
            'key_external_api' => 'eng.1',
        ])->create();

        CompetitionPhase::factory()->for($this->Competition)->create();

        $Games = $this
            ->CreateGameForExternalApi
            ->__invoke($this->Competition, (new \DateTime())->format('Y-m-d H:i:s'));

    }
}
