version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    container_name: lumen-bet-pool
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - "${APP_PORT}:80"
    networks:
      - bet-pool-net

  mongo:
    image: "mongo:5.0"
    container_name: mongodb-bet-pool
    command: mongod --auth
    restart: unless-stopped
    logging:
            driver: none
    ports:
      - "${DB_PORT_MONGODB}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME_MONGODB}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD_MONGODB}
    volumes:
      - /home/$USER/bet-pool/mongo-data:/data/db
      - /home/$USER/bet-pool/mongo-log:/var/log/mongodb/
    networks:
      - bet-pool-net

  redis:
    image: "redis:6.2.6"
    restart: unless-stopped
    container_name: redis-lumen-docker-skeleton
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${SERVER_REDIS_DB_EXPOSE_SERVICE}:6379"
    networks:
      - bet-pool-net

networks:
  bet-pool-net:
    external:
      name: external-environment-net
